server:
  model_name: ${oc.env:TINKER_SERVER_MODEL_NAME,Qwen/Qwen3-1.7B}
  host: ${oc.env:TINKER_SERVER_HOST,0.0.0.0}
  port: ${oc.env:TINKER_SERVER_PORT,8000}
  ray_address: ${oc.env:RAY_ADDRESS,local}
  checkpoint_dir: ${oc.env:TINKER_CHECKPOINT_DIR,/tmp/tinker-checkpoints}
  server_max_runtime: ${oc.env:TINKER_SERVER_MAX_RUNTIME,null} # an optional variable for the maximum uptime of the server, null means infinite
  max_concurrent_samples: ${oc.env:TINKER_SERVER_MAX_CONCURRENT_SAMPLES,32}
  enable_offload: true
  auto_merge_verl_default_config: true

actor_rollout_ref: # this is the same as verl's config, this field is ALWAYS required.
  actor:
    strategy: veomni
    ppo_mini_batch_size: 16
    veomni:
      cross_entropy_loss_implementation: chunk_loss
    optim:
      lr_scheduler_type: constant
      lr: 1.0e-06
  rollout:
    name: vllm
    tensor_model_parallel_size: 2
    gpu_memory_utilization: 0.6
  ref:
    enable: false
  model:
    path: ${oc.env:TINKER_SERVER_MODEL_PATH,Qwen/Qwen3-1.7B}

trainer:
  logger:
  - console
  project_name: verl_tinker_server
  experiment_name: tinker_server_actor_rollout
  nnodes: 1
  n_gpus_per_node: ${oc.env:TINKER_SERVER_N_GPUS_PER_NODE,8}
